

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."geostorm" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_id" "text" NOT NULL,
    "last24Hours" "jsonb",
    "last6Hours" "jsonb",
    "currentConditions" "jsonb",
    "next6Hours" "jsonb",
    "next24Hours" "jsonb",
    "activities" "text"
);


ALTER TABLE "public"."geostorm" OWNER TO "postgres";


COMMENT ON TABLE "public"."geostorm" IS 'Geostorm forecast data scraped from the Government of Canada website';



ALTER TABLE "public"."geostorm" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."geostorm_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."sun_moon" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_id" "text" NOT NULL,
    "toronto" "jsonb",
    "vancouver" "jsonb",
    "kosiv" "jsonb",
    "montreal" "jsonb",
    "heidelberg" "jsonb",
    "bristol" "jsonb",
    "snowdonia" "jsonb",
    "sayulita" "jsonb"
);


ALTER TABLE "public"."sun_moon" OWNER TO "postgres";


COMMENT ON TABLE "public"."sun_moon" IS 'Per-second records of current moon phase and azimuth of sun/moon';



ALTER TABLE "public"."sun_moon" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."supabase-demo_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."geostorm"
    ADD CONSTRAINT "geostorm_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."sun_moon"
    ADD CONSTRAINT "supabase-demo_pkey" PRIMARY KEY ("id");



CREATE POLICY "All users can read sun-moon data" ON "public"."sun_moon" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."geostorm" FOR SELECT USING (true);



CREATE POLICY "Machine user can insert geostorm data" ON "public"."geostorm" FOR INSERT TO "authenticated" WITH CHECK ((( SELECT ("auth"."jwt"() ->> 'sub'::"text")) = 'nasikwebsite-machine'::"text"));



CREATE POLICY "Machine user can insert sun-moon data" ON "public"."sun_moon" FOR INSERT TO "authenticated" WITH CHECK ((( SELECT ("auth"."jwt"() ->> 'sub'::"text")) = 'nasikwebsite-machine'::"text"));



ALTER TABLE "public"."geostorm" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."sun_moon" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";






ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."geostorm";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."sun_moon";



GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";








































































































































































GRANT ALL ON TABLE "public"."geostorm" TO "anon";
GRANT ALL ON TABLE "public"."geostorm" TO "authenticated";
GRANT ALL ON TABLE "public"."geostorm" TO "service_role";



GRANT ALL ON SEQUENCE "public"."geostorm_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."geostorm_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."geostorm_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."sun_moon" TO "anon";
GRANT ALL ON TABLE "public"."sun_moon" TO "authenticated";
GRANT ALL ON TABLE "public"."sun_moon" TO "service_role";



GRANT ALL ON SEQUENCE "public"."supabase-demo_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."supabase-demo_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."supabase-demo_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";






























RESET ALL;
